steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/ergtrack23-docker-images/api-cicd:${SHORT_SHA}",
        ".",
      ]
    env:
      - "DEV_ENV=prod"

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
      ]
