services:
  db_container:
    image: postgres:14.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres-docker
      - POSTGRES_PASSWORD=postgres-docker-pw
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: . #find dockerfile in this dir and build docker image
    depends_on:
      - db_container
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEV_ENV=docker_compose
    command: sh -c "python db_init_docker.py && alembic upgrade head && python src/loop.py"
    # uvicorn src.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./src:/ergtrack23api/src
      - ./alembic:/ergtrack23api/alembic
      - ./config:/ergtrack23api/config
      - ./tests:/ergtrack23api/tests
    # stdin_open: true # docker run -i
    # tty: true   

volumes:
  db:
    driver: local
