"""added Team table and added split_variance to workout_log table

Revision ID: 00a5d17a4e60
Revises: 9c119b3a9bbc
Create Date: 2023-08-24 16:48:33.306101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a5d17a4e60'
down_revision = '9c119b3a9bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.add_column('workout_log', sa.Column('split_variance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'split_variance')
    op.drop_table('team')
    # ### end Alembic commands ###
