"""added cols to user and logtable to accomodate teams

Revision ID: 0f0cdaef55c1
Revises: 00a5d17a4e60
Create Date: 2023-08-25 12:10:17.755084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0cdaef55c1'
down_revision = '00a5d17a4e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('team_admin', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['team'], ['team_id'])
    op.add_column('workout_log', sa.Column('post_to_team', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'post_to_team')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team_admin')
    op.drop_column('user', 'team')
    # ### end Alembic commands ###
