"""removed interval col from workout_log

Revision ID: 110bf60081fc
Revises: edda05671b5a
Create Date: 2023-05-15 12:24:59.071712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110bf60081fc'
down_revision = 'edda05671b5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'interval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log', sa.Column('interval', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
