"""initial revision. Create user and workout_log tables

Revision ID: 453a58e36300
Revises: 
Create Date: 2023-05-02 11:32:47.334626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '453a58e36300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_uid', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout_log',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(), nullable=True),
    sa.Column('stroke_rate', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Boolean(), nullable=True),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('subworkouts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_log')
    op.drop_table('user')
    # ### end Alembic commands ###
