"""Add watts and cal to WorkoutLogTable

Revision ID: 492f7a239b19
Revises: 6a9b0b258d29
Create Date: 2023-08-04 14:35:25.206338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492f7a239b19'
down_revision = '6a9b0b258d29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log', sa.Column('watts', sa.Integer(), nullable=True))
    op.add_column('workout_log', sa.Column('cal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'cal')
    op.drop_column('workout_log', 'watts')
    # ### end Alembic commands ###
