"""added fields to UserTable

Revision ID: 6a9b0b258d29
Revises: 110bf60081fc
Create Date: 2023-05-17 11:30:20.963098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a9b0b258d29"
down_revision = "110bf60081fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("sex", sa.String(), nullable=True))
    op.add_column("user", sa.Column("weight_class", sa.String(), nullable=True))
    op.add_column("user", sa.Column("para_class", sa.String(), nullable=True))
    op.add_column("user", sa.Column("country", sa.String(), nullable=True))
    op.add_column(
        "user", sa.Column("joined", sa.Date(), server_default="now()", nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "joined")
    op.drop_column("user", "country")
    op.drop_column("user", "para_class")
    op.drop_column("user", "weight_class")
    op.drop_column("user", "sex")
    op.drop_column("user", "age")
    # ### end Alembic commands ###
