"""dropped age added dob from UserTable

Revision ID: 8fc5c39feb94
Revises: 0f0cdaef55c1
Create Date: 2023-09-05 15:01:51.761334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc5c39feb94'
down_revision = '0f0cdaef55c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
