"""added heart rate column to workout table

Revision ID: 9c119b3a9bbc
Revises: 492f7a239b19
Create Date: 2023-08-17 11:43:33.046979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c119b3a9bbc'
down_revision = '492f7a239b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log', sa.Column('heart_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'heart_rate')
    # ### end Alembic commands ###
