"""added workout description col

Revision ID: edda05671b5a
Revises: 97b015525fea
Create Date: 2023-05-04 13:46:28.009631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edda05671b5a'
down_revision = '97b015525fea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log', 'description')
    # ### end Alembic commands ###
