name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ergtracker
  REGISTRY_NAME: ergtrack-api-github-actions
  IMAGE_NAME: api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY_NAME }}-${{ env.PROJECT_ID }}.pkg.dev
          username: _json_key
          password: ${{ secrets.ERGTRACK23_API_SA2 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_NAME }}-${{ env.PROJECT_ID }}.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest