name: Build and Push to Google Artifact Registry

on: pull_request

env:
  REGION: us-central1-docker.pkg.dev
  PROJECT_ID: ergtracker
  REGISTRY_NAME: ergtrack-api-github-actions
  IMAGE_NAME: api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGION }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}
          username: _json_key
          password: ${{ secrets.ERGTRACK23_API_SA2 }}

      - name: Build and push Docker test image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ env.REGION }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-test
      
      - name: Run tests
        run: |
          echo 'WARNING: test invocation is missing.'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGION }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}